var suntoryCommonHd =''
+'<!--probo_noindex-->\n'
+'<div id="suntoryCommonHd">\n'
+'<div id="gn_block_top" class="suntoryCommonHd_to_contents"><a href="?ke=hd#suntory_contents" id="to_contents" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_to_contents\',\'MouseDown\',this.href]});" tabindex="1">このページの本文へ移動</a></div>\n'
+'<div id="suntoryCommonHd_in">\n'
+'<div id="suntoryCommonHd_01">\n'
+'<div id="suntoryCommonHd_01_top">\n'
+'<h1><a href="https://www.suntory.co.jp/?ke=hd" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_hd\',\'MouseDown\',this.href]});" class=""><img src="//www.suntory.co.jp/sun_common/sun_navi/responsive/img/suntory_logo.svg" alt="水と生きる SUNTORY" width="288" height="25"></a></h1>\n'
+'<div id="suntoryCommonHd_sp_menu_btn">\n'
+'<button id="suntoryCommonHd_sp_menu_btn_trigger" aria-controls="suntoryCommonHd_menu" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'hb_close\']});"><span class="accessibilityHidden suntoryCommonHd_sp_menu_btn_close">メニューを開く</span><span class="accessibilityHidden suntoryCommonHd_sp_menu_btn_active">メニューを閉じる</span><span class="suntoryCommonHd_sp_menu_btn_line"></span></button>\n'
+'</div>\n'
+'</div>\n'
+'<div id="suntoryCommonHd_menu">\n'
+'<div id="suntoryCommonHd_menu_search_sp">\n'
+'<form method="get" action="https://ssl1.suntory.co.jp/search/ja_all/?ke=hd" accept-charset="UTF-8" id="suntoryCommonHd_menu_search_sp_inner">\n'
+'<input type="text" name="q" value="" autocomplete="off" placeholder="サイト内を探す" id="suntoryCommonHd_menu_search_sp_input">\n'
+'<button type="submit" value="検索" id="suntoryCommonHd_menu_search_sp_submit" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_hd\',\'MouseDown\',\'SEARCH\']});"><span class="accessibilityHidden">検索</span><span class="suntoryCommonHd_menu_search_glass"></span></button>\n'
+'</form>\n'
+'</div>\n'
+'<div id="suntoryCommonHd_menu_inner">\n'
+'<div id="suntoryCommonHd_menu_inner_column">\n'
+'<div class="suntoryCommonHd_sp_menu_foot_wrap">\n'
+'<nav id="suntoryCommonHd_sp_menu_foot">\n'
+'<p class="suntoryCommonHd_sp_menu_foot_item"><a href="https://www.suntory.co.jp/factory/?ke=mn" class="suntoryCommonHd_sp_menu_foot_item_link" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><img src="//www.suntory.co.jp/sun_common/sun_navi/responsive/img/img_banner_factorip.svg" alt="工場行こうファクトリップ" class="suntoryCommonHd_sp_menu_foot_item_link_img" width="160" height="50" loading="lazy"></a></p>\n'
+'<p class="suntoryCommonHd_sp_menu_foot_item"><a href="https://www.suntory.co.jp/company/quality/?ke=mn" class="suntoryCommonHd_sp_menu_foot_item_link" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><img src="//www.suntory.co.jp/sun_common/sun_navi/responsive/img/img_banner_quality.svg" alt="ものづくり・品質" class="suntoryCommonHd_sp_menu_foot_item_link_img" width="160" height="50" loading="lazy"></a></p>\n'
+'<p class="suntoryCommonHd_sp_menu_foot_item"><a href="https://www.suntory.co.jp/company/mizutoikiru/?ke=mn" class="suntoryCommonHd_sp_menu_foot_item_link" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><img src="//www.suntory.co.jp/sun_common/sun_navi/responsive/img/img_banner_mizutoikiru.svg" alt="水と生きる＠リアル" class="suntoryCommonHd_sp_menu_foot_item_link_img" width="160" height="50" loading="lazy"></a></p>\n'
+'<p class="suntoryCommonHd_sp_menu_foot_item"><a href="https://www.suntory.co.jp/arp/?ke=mn" class="suntoryCommonHd_sp_menu_foot_item_link" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><img src="//www.suntory.co.jp/sun_common/sun_navi/responsive/img/img_banner_drink_smart.svg" alt="DRINK SMART" class="suntoryCommonHd_sp_menu_foot_item_link_img" width="160" height="50" loading="lazy"></a></p>\n'
+'</nav>\n'
+'</div>\n'
+'<div id="suntoryCommonHd_upper">\n'
+'<ul id="suntoryCommonHd_menu_01">\n'
+'<li class="btn_01"><a href="https://www.suntory.com/?ke=hd" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_hd\',\'MouseDown\',this.href]});" target="_blank" rel="noopener" lang="en">Global<span class="accessibilityHidden">新しいウィンドウで開く</span></a></li>\n'
+'<li class="btn_02"><a href="https://id.suntory.co.jp/api/connect/v1/authz?response_type=code&scope=openid&client_id=cid2205002&state=temporarystate&redirect_uri=https%3A%2F%2Fid.suntory.co.jp%2Fuser%2Freference&nonce=temporarynonce&prompt=login&ke=hd" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_hd\',\'MouseDown\',this.href]});">マイページ</a></li>\n'
+'<li class="btn_03"><a href="https://www.suntory.co.jp/customer/?ke=hd" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_hd\',\'MouseDown\',this.href]});">お問い合わせ</a></li>\n'
+'</ul>\n'
+'<div id="suntoryCommonHd_submenu_search">\n'
+'<form method="get" action="https://ssl1.suntory.co.jp/search/ja_all/?ke=hd" accept-charset="UTF-8" id="suntoryCommonHd_submenu_search_inner">\n'
+'<button type="button" id="suntoryCommonHd_submenu_search_open" data-search-toggle="" aria-expanded="false" aria-controls="suntoryCommonHd_submenu_search_input"><span class="suntoryCommonHd_submenu_search_open_text">検索窓を開く</span><span class="suntoryCommonHd_submenu_search_glass"></span></button>\n'
+'<input type="text" name="q" value="" autocomplete="off" placeholder="サイト内を探す" id="suntoryCommonHd_submenu_search_input" aria-hidden="true">\n'
+'<button type="submit" value="検索" id="suntoryCommonHd_submenu_search_submit" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_hd\',\'MouseDown\',\'SEARCH\']});"><span class="suntoryCommonHd_submenu_search_submit_text">検索</span><span class="suntoryCommonHd_submenu_search_glass"></span></button>\n'
+'</form>\n'
+'</div>\n'
+'</div>\n'
+'<nav id="suntoryCommonHd_below">\n'
+'<ul id="suntoryCommonHd_menu_02">\n'
+'<li class="suntoryCommonHd_menu_02_list suntoryCommonHd_menu_02_list_01">\n'
+'<a href="https://products.suntory.co.jp/?ke=hd" class="suntoryCommonHd_menu_02_list_item" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_hd\',\'MouseDown\',this.href]});">商品</a>\n'
+'</li>\n'
+'<li class="suntoryCommonHd_menu_02_list suntoryCommonHd_menu_02_list_02">\n'
+'<button class="suntoryCommonHd_menu_02_list_item suntoryCommonHd_menu_02_dropdown_list_item_arrow" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_hd\',\'MouseDown\',\'enjoy\']});" aria-controls="suntoryCommonHd_menu_02_list_02_dropdown" aria-expanded="false">知る・楽しむ</button>\n'
+'<div class="suntoryCommonHd_menu_02_dropdown" id="suntoryCommonHd_menu_02_list_02_dropdown" aria-hidden="true">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_inner">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_head">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_head_ttl suntoryCommonHd_menu_02_dropdown_head_ttl_back"><button onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'hb_return\']});"><span>もどる</span></button></div>\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_head_ttl"><a href="https://ssl1.suntory.co.jp/enjoy/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});">知る・楽しむTOP</a></div>\n'
+'</div>\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_body">\n'
+'<ul class="suntoryCommonHd_menu_02_dropdown_list">\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_wrap">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_list_ttl"><span class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_pc">キャンペーン</span><button class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_sp" aria-controls="suntoryCommonHd_menu_02_list_02_dropdown_links_01" aria-expanded="false">キャンペーン</button></div>\n'
+'<ul class="suntoryCommonHd_menu_02_dropdown_list_links" id="suntoryCommonHd_menu_02_list_02_dropdown_links_01">\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item suntoryCommonHd_menu_02_dropdown_list_item_back"><button onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'hb_return\']});"><span>もどる</span></button></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://ssl1.suntory.co.jp/enjoy/campaign/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>キャンペーン一覧</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://ssl1.suntory.co.jp/enjoy/et/game/gamelist?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>会員限定ポイントをためる</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://ssl1.suntory.co.jp/enjoy/et/campaign/point?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>会員限定ポイントをつかう</span></a></li>\n'
+'</ul>\n'
+'</li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_wrap">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_list_ttl"><span class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_pc">知る・体感する</span><button class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_sp" aria-controls="suntoryCommonHd_menu_02_list_02_dropdown_links_02" aria-expanded="false">知る・体感する</button></div>\n'
+'<ul class="suntoryCommonHd_menu_02_dropdown_list_links suntoryCommonHd_menu_02_dropdown_list_links_2col menu_02_dropdown_list_item_column" id="suntoryCommonHd_menu_02_list_02_dropdown_links_02">\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item suntoryCommonHd_menu_02_dropdown_list_item_back"><button onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'hb_return\']});"><span>もどる</span></button></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/factory/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>工場見学へ行こう</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/area/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>地域情報</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.youtube.com/user/SuntoryGroup?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});" target="_blank"><span>CM・動画（公式YouTube）</span><span class="accessibilityHidden">新しいウィンドウで開く</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://recipe.suntory.co.jp/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>お料理・お酒レシピ</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://gourmet.suntory.co.jp/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>サントリーグルメガイド</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://bar-navi.suntory.co.jp/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>バー検索サイト BAR-NAVI</span></a></li>\n'
+'</ul>\n'
+'</li>\n'
+'</ul>\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_head_close"><button class="suntoryCommonHd_menu_02_dropdown_head_close_btn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'close\']});"><span class="suntoryCommonHd_menu_02_dropdown_head_close_line"></span><span class="suntoryCommonHd_menu_02_dropdown_head_close_text">閉じる</span></button></div>\n'
+'</div>\n'
+'</div>\n'
+'</div>\n'
+'</li>\n'
+'<li class="suntoryCommonHd_menu_02_list suntoryCommonHd_menu_02_list_03">\n'
+'<button class="suntoryCommonHd_menu_02_list_item suntoryCommonHd_menu_02_dropdown_list_item_arrow" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_hd\',\'MouseDown\',\'culture-sports\']});" aria-controls="suntoryCommonHd_menu_02_list_03_dropdown" aria-expanded="false">文化・スポーツ</button>\n'
+'<div class="suntoryCommonHd_menu_02_dropdown" id="suntoryCommonHd_menu_02_list_03_dropdown" aria-hidden="true">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_inner">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_head">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_head_ttl suntoryCommonHd_menu_02_dropdown_head_ttl_back"><button onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'hb_return\']});"><span>もどる</span></button></div>\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_head_ttl"><a href="https://www.suntory.co.jp/culture-sports/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});">文化・スポーツTOP</a></div>\n'
+'</div>\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_body">\n'
+'<ul class="suntoryCommonHd_menu_02_dropdown_list suntoryCommonHd_menu_02_dropdown_list_2col">\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_wrap">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_list_ttl"><span class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_pc">芸術・文化・学術</span><button class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_sp" aria-controls="suntoryCommonHd_menu_02_list_03_dropdown_links_01" aria-expanded="false">芸術・文化・学術</button></div>\n'
+'<ul class="suntoryCommonHd_menu_02_dropdown_list_links suntoryCommonHd_menu_02_dropdown_list_links_2col" id="suntoryCommonHd_menu_02_list_03_dropdown_links_01">\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item suntoryCommonHd_menu_02_dropdown_list_item_back"><button onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'hb_return\']});"><span>もどる</span></button></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/suntoryhall/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>サントリーホール</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/sma/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>サントリー美術館</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/sfa/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>サントリー芸術財団</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/sfnd/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>サントリー文化財団</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.sunbor.or.jp/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});" target="_blank" rel="noopener"><span>サントリー生命科学財団</span><span class="accessibilityHidden">新しいウィンドウで開く</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/culture-sports/daiku/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>サントリー1万人の第九</span></a></li>\n'
+'</ul>\n'
+'</li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_wrap">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_list_ttl"><span class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_pc">スポーツ</span><button class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_sp" aria-controls="suntoryCommonHd_menu_02_list_03_dropdown_links_02" aria-expanded="false">スポーツ</button></div>\n'
+'<ul class="suntoryCommonHd_menu_02_dropdown_list_links suntoryCommonHd_menu_02_dropdown_list_links_2col" id="suntoryCommonHd_menu_02_list_03_dropdown_links_02">\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item suntoryCommonHd_menu_02_dropdown_list_item_back"><button onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'hb_return\']});"><span>もどる</span></button></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/culture-sports/sungoliath/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>ラグビーチーム<br>東京サントリーサンゴリアス</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/culture-sports/sunbirds/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>バレーボールチーム<br>サントリーサンバーズ</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/culture-sports/slo/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>宮里藍<br>サントリーレディスオープン</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/culture-sports/dreammatch/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>サントリードリームマッチ</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/culture-sports/challengedsports/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>チャレンジド・スポーツ<br>プロジェクト</span></a></li>\n'
+'</ul>\n'
+'</li>\n'
+'</ul>\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_head_close"><button class="suntoryCommonHd_menu_02_dropdown_head_close_btn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'close\']});"><span class="suntoryCommonHd_menu_02_dropdown_head_close_line"></span><span class="suntoryCommonHd_menu_02_dropdown_head_close_text">閉じる</span></button></div>\n'
+'</div>\n'
+'</div>\n'
+'</div>\n'
+'</li>\n'
+'<li class="suntoryCommonHd_menu_02_list suntoryCommonHd_menu_02_list_04">\n'
+'<button class="suntoryCommonHd_menu_02_list_item suntoryCommonHd_menu_02_dropdown_list_item_arrow" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_hd\',\'MouseDown\',\'sustainability\']});" aria-controls="suntoryCommonHd_menu_02_list_04_dropdown" aria-expanded="false">サステナビリティ</button>\n'
+'<div class="suntoryCommonHd_menu_02_dropdown" id="suntoryCommonHd_menu_02_list_04_dropdown" aria-hidden="true">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_inner">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_head">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_head_ttl suntoryCommonHd_menu_02_dropdown_head_ttl_back"><button onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'hb_return\']});"><span>もどる</span></button></div>\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_head_ttl"><a href="https://www.suntory.co.jp/company/csr/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});">サステナビリティTOP</a></div>\n'
+'</div>\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_body">\n'
+'<ul class="suntoryCommonHd_menu_02_dropdown_list">\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_wrap">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_list_ttl"><span class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_pc">サントリーのサステナビリティ経営</span><button class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_sp" aria-controls="suntoryCommonHd_menu_02_list_04_dropdown_links_01" aria-expanded="false">サントリーのサステナビリティ経営</button></div>\n'
+'<ul class="suntoryCommonHd_menu_02_dropdown_list_links suntoryCommonHd_menu_02_dropdown_list_links_2col" id="suntoryCommonHd_menu_02_list_04_dropdown_links_01">\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item suntoryCommonHd_menu_02_dropdown_list_item_back"><button onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'hb_return\']});"><span>もどる</span></button></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/company/csr/commitment/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>トップメッセージ</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/company/csr/management/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>サステナビリティビジョン</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/company/csr/?ke=mn#EsgArea" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>ESGの取り組み</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/company/csr/data/data/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>関連データ</span></a></li>\n'
+'</ul>\n'
+'</li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_wrap">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_list_ttl"><span class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_pc">活動事例</span><button class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_sp" aria-controls="suntoryCommonHd_menu_02_list_04_dropdown_links_02" aria-expanded="false">活動事例</button></div>\n'
+'<ul class="suntoryCommonHd_menu_02_dropdown_list_links suntoryCommonHd_menu_02_dropdown_list_links_2col" id="suntoryCommonHd_menu_02_list_04_dropdown_links_02">\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item suntoryCommonHd_menu_02_dropdown_list_item_back"><button onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'hb_return\']});"><span>もどる</span></button></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/eco/forest/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>サントリー 天然水の森</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/eco/birds/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>サントリーの愛鳥活動</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://mizuiku.suntory.jp/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>サントリー「水育」</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/eco/teigen/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>サントリーのエコ活</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/company/csr/story/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>サステナビリティストーリーズ</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/company/peopleculture/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>「人は資本」の経営</span></a></li>\n'
+'</ul>\n'
+'</li>\n'
+'</ul>\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_head_close"><button class="suntoryCommonHd_menu_02_dropdown_head_close_btn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'close\']});"><span class="suntoryCommonHd_menu_02_dropdown_head_close_line"></span><span class="suntoryCommonHd_menu_02_dropdown_head_close_text">閉じる</span></button></div>\n'
+'</div>\n'
+'</div>\n'
+'</div>\n'
+'</li>\n'
+'<li class="suntoryCommonHd_menu_02_list suntoryCommonHd_menu_02_list_05">\n'
+'<button class="suntoryCommonHd_menu_02_list_item suntoryCommonHd_menu_02_dropdown_list_item_arrow" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_hd\',\'MouseDown\',\'company\']});" aria-controls="suntoryCommonHd_menu_02_list_05_dropdown" aria-expanded="false">企業情報</button>\n'
+'<div class="suntoryCommonHd_menu_02_dropdown" id="suntoryCommonHd_menu_02_list_05_dropdown" aria-hidden="true">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_inner">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_head">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_head_ttl suntoryCommonHd_menu_02_dropdown_head_ttl_back"><button onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'hb_return\']});"><span>もどる</span></button></div>\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_head_ttl"><a href="https://www.suntory.co.jp/company/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});">企業情報TOP</a></div>\n'
+'</div>\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_body">\n'
+'<ul class="suntoryCommonHd_menu_02_dropdown_list suntoryCommonHd_menu_02_dropdown_list_4col">\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_wrap">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_list_ttl"><span class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_pc">企業理念</span><button class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_sp" aria-controls="suntoryCommonHd_menu_02_list_05_dropdown_links_01" aria-expanded="false">企業理念</button></div>\n'
+'<ul class="suntoryCommonHd_menu_02_dropdown_list_links" id="suntoryCommonHd_menu_02_list_05_dropdown_links_01">\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item suntoryCommonHd_menu_02_dropdown_list_item_back"><button onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'hb_return\']});"><span>もどる</span></button></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/company/topmessage/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>トップメッセージ</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/company/philosophy/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>グループ企業理念</span></a></li>\n'
+'</ul>\n'
+'</li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_wrap">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_list_ttl"><span class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_pc">会社案内</span><button class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_sp" aria-controls="suntoryCommonHd_menu_02_list_05_dropdown_links_02" aria-expanded="false">会社案内</button></div>\n'
+'<ul class="suntoryCommonHd_menu_02_dropdown_list_links" id="suntoryCommonHd_menu_02_list_05_dropdown_links_02">\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item suntoryCommonHd_menu_02_dropdown_list_item_back"><button onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'hb_return\']});"><span>もどる</span></button></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/company/overview/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>企業概要</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/company/group/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>グループ企業一覧</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/company/branch/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>事業所一覧</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/company/business/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>事業紹介</span></a></li>\n'
+'</ul>\n'
+'</li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_wrap">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_list_ttl"><span class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_pc">財務・人材・採用</span><button class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_sp" aria-controls="suntoryCommonHd_menu_02_list_05_dropdown_links_03" aria-expanded="false">財務・人材・採用</button></div>\n'
+'<ul class="suntoryCommonHd_menu_02_dropdown_list_links" id="suntoryCommonHd_menu_02_list_05_dropdown_links_03">\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item suntoryCommonHd_menu_02_dropdown_list_item_back"><button onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'hb_return\']});"><span>もどる</span></button></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/company/financial/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>財務情報</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/recruit/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>採用情報</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/company/peopleculture/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>「人は資本」の経営</span></a></li>\n'
+'</ul>\n'
+'</li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_wrap">\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_list_ttl"><span class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_pc">品質・安全・技術</span><button class="suntoryCommonHd_menu_02_dropdown_list_item_arrow suntoryCommonHd_menu_02_dropdown_list_sp" aria-controls="suntoryCommonHd_menu_02_list_05_dropdown_links_04" aria-expanded="false">品質・安全・技術</button></div>\n'
+'<ul class="suntoryCommonHd_menu_02_dropdown_list_links" id="suntoryCommonHd_menu_02_list_05_dropdown_links_04">\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item suntoryCommonHd_menu_02_dropdown_list_item_back"><button onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'hb_return\']});"><span>もどる</span></button></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/company/quality/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>安全・安心への取り組み</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/company/research/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>研究開発への取り組み</span></a></li>\n'
+'<li class="suntoryCommonHd_menu_02_dropdown_list_item"><a href="https://www.suntory.co.jp/company/digital/?ke=mn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',this.href]});"><span>デジタルへの取り組み</span></a></li>\n'
+'</ul>\n'
+'</li>\n'
+'</ul>\n'
+'<div class="suntoryCommonHd_menu_02_dropdown_head_close"><button class="suntoryCommonHd_menu_02_dropdown_head_close_btn" onmousedown="dataLayer.push({event:\'gaEvent\',params:[\'sun_navi_menu\',\'MouseDown\',\'close\']});"><span class="suntoryCommonHd_menu_02_dropdown_head_close_line"></span><span class="suntoryCommonHd_menu_02_dropdown_head_close_text">閉じる</span></button></div>\n'
+'</div>\n'
+'</div>\n'
+'</div>\n'
+'</li>\n'
+'</ul>\n'
+'</nav>\n'
+'</div>\n'
+'</div>\n'
+'</div>\n'
+'</div>\n'
+'<!--/suntoryCommonHd_01-->\n'
+'</div>\n'
+'<!--/suntoryCommonHd_in-->\n'
+'</div>\n'
+'<!--/suntoryCommonHd-->\n'
+'<!--/probo_noindex-->\n'
;
document.getElementById('suntoryCommonHeader').insertAdjacentHTML('afterbegin',suntoryCommonHd);